#!/Users/dino/.venv/bin/python

from __future__ import annotations

import os
import oci

from typing import Tuple, Any
from config import config, YELLOW, RESET
from policy import policy_management
from dotenv import load_dotenv
from compartiment import compartment_management
from inquire_managment import inquire_display_dict, inquire_display_process

load_dotenv()

def check_users_permissions(identity_client: oci.identity.IdentityClient, tenancy_id) -> bool:
    permission_list = {
        "Compartments": identity_client.list_compartments,
        "Policies": identity_client.list_policies,
        "Users": identity_client.list_users,
        "Groups": identity_client.list_groups
    }

    all_passed = True
    print(f"\n🔍 {YELLOW}Checking IAM Permissions...{RESET} {config["username"]}")
    for resource, methode in permission_list.items():
        try:
            if methode(compartment_id=tenancy_id, limit=1) == 1:
                print(f"✅ Permissions verified: User can list {resource}.")
        except oci.exceptions.ServiceError as e:
            if e.status == 403:
                print(f"❌ {resource} Access Denied: User does not have permissions.")
                all_passed = False
            else:
                print(f"⚠️ OCI Service Error: {e.message}")
                all_passed = False
        except Exception as e:
            print(f"❌ Connection error: {e}")
            all_passed = False
    return all_passed

def inquirer_oci_domains() -> str:
    env_vars = dict(os.environ)
    oci_domains = {key: value for key, value in env_vars.items() if "DOMAIN" in key}

    answers = inquire_display_dict(oci_domains, "Which domain do you need ?")
    domain_url = oci_domains[answers]

    return domain_url

def inquirer_oci_users(config_file) -> dict[str, list[Any] | Any]:
    domain_url = inquirer_oci_domains()

    identity_domains_client = oci.identity_domains.IdentityDomainsClient(config_file, domain_url)
    response = identity_domains_client.list_users(attributes="userName,groups,ocid")

    users_list = {}

    for user in response.data.resources:
        user_info = {
            "user_name": user.user_name,
            "user_id": user.id,
            "user_ocid": user.ocid,
            "groups": []
        }
        if hasattr(user, 'groups') and user.groups:
            for group in user.groups:
                group_data = {
                    "group_name": group.display,
                    "group_id": group.value,
                    "ocid": group.ocid
                }
                user_info["groups"].append(group_data)
        else:
            print("  - Aucun groupe")
        users_list[user.user_name] = user_info
    selected_user_name = inquire_display_dict(users_list, "Which user do you want ?")
    selected_user_credentials = users_list[selected_user_name]
    return selected_user_credentials

def main():
    try:
        while True:
            process = inquire_display_process()
            if process != "exit":
                config_file = oci.config.from_file("~/.oci/config")
                selected_user_credentials = inquirer_oci_users(config_file)
                config["username"] = selected_user_credentials["user_name"]
                config["oci_config"] = oci.config.from_file(
                    "~/.oci/config",
                    selected_user_credentials["user_name"]
                )
                identity_client = oci.identity.IdentityClient(config["oci_config"])
                check_users_permissions(identity_client, config["oci_config"]["tenancy"])
                if "new compartment" in process:
                    compartment_management(selected_user_credentials, config)
                elif "new policy" in process:
                    policy_management(selected_user_credentials)
                elif "new user" in process:
                    policy_management(selected_user_credentials)
                elif "new group" in process:
                    policy_management(selected_user_credentials)
                break
            elif "exit" in process:
                print("break process...")
                break
            else:
                print("please input Y/n")
    except oci.exceptions.ConfigFileNotFound as e:
        print(f'OCI ERROR Config file not found: {e}')
    except oci.exceptions.ClientError as e:
        print(f"OCI ERROR client error: {e}")
    except oci.exceptions.ConnectTimeout as e:
        print(f"OCI ERROR timeout: {e}")
    except Exception as e:
        print(f"Error in main methode: {e}")

if __name__ == "__main__":
    main()